  services: 
  - name: FirstBluePrint
    type: web
    runtime: node
    repo : https://github.com/Medmat0/BleuPrintAPP
    region: frankfurt
    plan: free
    buildCommand: npm install 
    startCommand: npm start
    envVars:
      - key: DBfirstBlue_URL
        fromDatabase:
            name: FirstBluePrintDB
            property: connectionString

databases:
   - name: FirstBluePrintDB
     databaseName: DBfirstBlue
     region: frankfurt
     plan: free

